[build]
    publish = "build/"
    command = "npm run build"

[[redirects]]
    from = "/api/*"
    to = "https://my-backend.herokuapp.com/api/:splat"
    status = 200

[[redirects]]
    from = "/auth/*"
    to = "https://my-backend.herokuapp.com/auth/:splat"
    status = 200

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200